### ISSUE TITLE
How do I use public STUN and TURN servers?

### ISSUE THREAD

**Issue by hayzamjs** [AndresCalimero/gvcp#1]
Can you show me how to integrate this into gvcp? Thanks and the application is really great!

`

1
--
{url:'stun:stun01.sipphone.com'},
  | {url:'stun:stun.ekiga.net'},
  | {url:'stun:stun.fwdnet.net'},
  | {url:'stun:stun.ideasip.com'},
  | {url:'stun:stun.iptel.org'},
  | {url:'stun:stun.rixtelecom.se'},
  | {url:'stun:stun.schlund.de'},
  | {url:'stun:stun.l.google.com:19302'},
  | {url:'stun:stun1.l.google.com:19302'},
  | {url:'stun:stun2.l.google.com:19302'},
  | {url:'stun:stun3.l.google.com:19302'},
  | {url:'stun:stun4.l.google.com:19302'},
  | {url:'stun:stunserver.org'},
  | {url:'stun:stun.softjoys.com'},
  | {url:'stun:stun.voiparound.com'},
  | {url:'stun:stun.voipbuster.com'},
  | {url:'stun:stun.voipstunt.com'},
  | {url:'stun:stun.voxgratia.org'},
  | {url:'stun:stun.xten.com'},
  | {
  | url: 'turn:numb.viagenie.ca',
  | credential: 'muazkh',
  | username: 'webrtc@live.com'
  | },
  | {
  | url: 'turn:192.158.29.39:3478?transport=udp',
  | credential: 'JZEOEt2V3Qb0y27GRntt2u2PAYA=',
  | username: '28224511:1379330808'
  | },
  | {
  | url: 'turn:192.158.29.39:3478?transport=tcp',
  | credential: 'JZEOEt2V3Qb0y27GRntt2u2PAYA=',
  | username: '28224511:1379330808'
  | }

`

**Comment by AndresCalimero** [comment]
Yes, and I'm glad you found it useful!

You need to edit the config.json file located inside the config folder, more info [here](https://github.com/AndresCalimero/gvcp/blob/master/config/README.md)

Note that GVCP uses time-limited TURN credentials so you will need a secret key and an expiry time (instead of providing the credential and the username directly), more info [here](https://stackoverflow.com/a/35767224)

Attached you will find an example of the config.json file with your stun and turn servers.

[config.zip](https://github.com/AndresCalimero/gvcp/files/1133329/config.zip)

**Comment by hayzamjs** [comment]
Thanks buddy!
